Repository mosdef-hub/mbuild, pull requests merged in 2019-05, with the labels that each got.

#532 Update installation docs
  docs/installation.rst
Labels: documentation

#520 Add Python 3.6 to Appveyor
  appveyor.yml
Labels: maintenance, testing

#522 Implement some style suggestions by linters
  .coveragerc
  mbuild/box.py
  mbuild/compound.py
  mbuild/examples/alkane/alkane.py
  mbuild/examples/alkane_monolayer/alkane_monolayer.py
  mbuild/examples/bilayer/bilayer.py
  mbuild/examples/lennard_jones/monolj.py
  mbuild/examples/pmpc/brush.py
  mbuild/examples/pmpc/pmpc_brush_layer.py
  mbuild/formats/gsdwriter.py
  mbuild/lattice.py
  mbuild/lib/recipes/monolayer.py
  mbuild/lib/recipes/silica_interface.py
  mbuild/lib/surfaces/betacristobalite.py
  mbuild/packing.py
  mbuild/tests/test_box.py
  mbuild/tests/test_compound.py
  mbuild/tests/test_utils.py
Labels: maintenance

#456 Write nbfix_types to LAMMPS data file
  docs/conf.py
  mbuild/formats/lammpsdata.py
  mbuild/tests/test_lammpsdata.py
Labels: feature

#545 Remove duplicate visualization in py3dmol
  mbuild/compound.py
Labels: bug
