Repository mosdef-hub/mbuild, pull requests merged in 2019-03, with the labels that each got.

#460 Initial implementation of fill_sphere packing function
  mbuild/packing.py
  mbuild/tests/test_packing.py
Labels: feature

#500 Draft of a contributors guide
  CONTRIBUTING.md
Labels: documentation, maintenance

#498 Add some issue/PR templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/QUESTION.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, maintenance

#435 Support Python 3.6
  .travis.yml
  devtools/conda-recipe/meta.yaml
  requirements-dev.txt
Labels: low priority, maintenance

#515 Remove unused internal function
  mbuild/packing.py
Labels: maintenance

#516 Drop glotzer and bioconda channels
  .travis.yml
  appveyor.yml
Labels: maintenance, testing
