Repository mosdef-hub/mbuild, pull requests merged in 2021-04, with the labels that each got.

#850 Add conda yml files
  Dockerfile
  azure-pipelines.yml
  docs/installation.rst
  environment-dev.yml
  environment-win.yml
  environment.yml
  mbuild/conversion.py
  mbuild/tests/test_compound.py
  requirements-dev.txt
  requirements.txt
Labels: discussion

#839 Functionality to update a port's separation and orientation after it has already been created
  mbuild/port.py
  mbuild/tests/test_port.py
Labels: feature

#890 Install jupyter so the entrypoint does not fail
  Dockerfile
Labels: maintenance
